name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: |
          echo "🔨 Building Next.js app..."
          npm run ci:build

          echo "📂 Checking .next directory..."
          if [ -d ".next" ]; then
            echo "✅ .next directory exists"
            echo "File count: $(find .next -type f | wc -l)"
            echo "Directory size: $(du -sh .next)"
          else
            echo "❌ Build failed: .next directory not found"
            exit 1
          fi

      - name: Create build archive
        run: |
          echo "📦 Creating tarball of .next..."
          tar -czf build-files.tar.gz .next
          echo "Archive created: $(ls -la build-files.tar.gz)"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-archive
          path: build-files.tar.gz
          retention-days: 7
          if-no-files-found: error
